### PR TITLE
Chinese (zh) translation finished

### PR DESCRIPTION
**Pull request by andyden9**
please proofread and comment thanks

### CODE REVIEW

**Comment by 0xclem** [comment]
Hey @andyden9, thanks for your PR. Because of the next release we had to make some minor changes to the initial EN json file. Would you mind fixing your PR so it can use the latest updates?

Easiest way would be to start again from the new `en/translation.json` file as its structure changed a bit. Sorry again for the inconvenience.

FYI, here are the changes: https://github.com/Synthetixio/synthetix-translations/pull/3/files#diff-6000b66f2ed7c8f8c4e193a38d780897

**Comment by 0xclem** [comment]
@andyden9 also can you please make the PR to `master` branch and not `onboarding`? You might have to close this one.

**Comment by andyden9** [comment]
@clementbalestrat yeah sure no prob

**Comment by andyden9** [comment]
I didn't log in here haha sorry, will do asap

**Comment by 0xclem** [comment]
@andyden9 no worries!

**Pull request closed without merging**
